jobs:
- deployment: deployment_dev
  displayName: 'Dev'
  #pool: '$(poolName)'
  environment: 'dev'
  # condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature'))
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../templates/deployment/deployment.yml

- deployment: deployment_uat
  displayName: 'UAT'
  pool: '$(poolName)'
  environment: 'test'
  # condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature'))
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../templates/deployment/deployment.yml

- deployment: deployment_prod
  displayName: 'Prod'
  pool: '$(poolName)'
  environment: 'prod'
  # condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature'))
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../templates/deployment/deployment.yml