parameters:
  pool: 'rac-pool'
  azureSubscriptionName: 'DevTest'

jobs:
- deployment: deployment_dev
  displayName: 'Dev'
  pool: '${{ parameters.pool }}'
  environment: 'dev'
  condition: succeeded()
  # condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature'))
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../templates/deployment/deployment.yml
          parameters:
            azureSubscriptionName: ''
            WebAppName: ''


- deployment: deployment_uat
  displayName: 'UAT'
  pool: '${{ parameters.pool }}'
  environment: 'test'
  condition: succeeded()
  # condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature'))
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../templates/deployment/deployment.yml
          parameters:
            azureSubscriptionName: ''
            WebAppName: ''

- deployment: deployment_prod
  displayName: 'Prod'
  pool: '${{ parameters.pool }}'
  environment: 'prod'
  condition: succeeded()
  # condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature'))
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../templates/deployment/deployment.yml
          parameters:
            azureSubscriptionName: ''
            WebAppName: ''