parameters:
  pool: 'rac-pool'
  azureSubscriptionName: 'DevTest'
  webAppName: ''
  functionName: ''

jobs:
- deployment: deployment_dev
  displayName: 'Dev'
  pool: '${{ parameters.pool }}'
  environment: 'dev'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../templates/deployment/deployment.yml
          parameters:
            azureSubscriptionName: '${{ parameters.azureSubscriptionName }}'
            pool: '${{ parameters.pool }}'
            WebAppName: '${{ parameters.WebAppName }}'
            functionName: '${{ parameters.functionName }}'

- deployment: deployment_uat
  displayName: 'UAT'
  pool: '${{ parameters.pool }}'
  environment: 'test'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], '/refs/tags/v'))
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../templates/deployment/deployment.yml
          parameters:
            azureSubscriptionName: '${{ parameters.azureSubscriptionName }}'
            pool: '${{ parameters.pool }}'
            WebAppName: '${{ parameters.WebAppName }}'
            functionName: '${{ parameters.functionName }}'

- deployment: deployment_prod
  displayName: 'Prod'
  pool: '${{ parameters.pool }}'
  environment: 'prod'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], '/refs/tags/v'))
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../templates/deployment/deployment.yml
          parameters:
            azureSubscriptionName: '${{ parameters.azureSubscriptionName }}'
            pool: '${{ parameters.pool }}'
            WebAppName: '${{ parameters.WebAppName }}'
            functionName: '${{ parameters.functionName }}'