parameters:
  pool: 'windows-latest'
  cleanCheckout: 'false'
  azureSubscription: 'DevTest'
  buildConfiguration: 'Release'
  sonarCloudProjectKey: ''
  sonarCloudextraProperties: ''
  coverletCoverageExclusions: ''
  integrationTestsAppSettingsTransform: ''
  solutionType: ''
  functionName: ''
  webAppName: ''

jobs:
- job:
  displayName: 'Build & Test .Net Core'
  pool:
    vmImage: ${{ parameters.pool }}

  # Reference templae for setting up build tools
  steps:
  - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
    clean: ${{ parameters.cleanCheckout }}  # whether to fetch clean each time

# Restore NuGet packages and build VS solution
  - template: ../templates/vsBuild/dotnetBuild.yml
    parameters:
      buildConfiguration: '${{ parameters.buildConfiguration }}'

  # Executes the Donet CLI publish command to package the application
  - template: ../templates/publishArtifacts/dotnetPublish.yml
    parameters:
      buildConfiguration: '${{ parameters.buildConfiguration }}'
      functionName: '${{ parameters.functionName }}'
      webAppName: '${{ parameters.webAppName }}'

# # Runs White Source step
#   - template: ../templates/whiteSource/whiteSource.yml

# Publish artifacts
  - template: ../templates/publishArtifacts/publishArtifacts.yml
    parameters:
      buildConfiguration: '${{ parameters.buildConfiguration }}'
